Resolve Xcode 9 build failures
material-motion/material-motion-swift pull request #123
Opened 2017-10-26 13:35 UTC by jverkoey

2017-10-31 15:52 UTC, romoore requested changes
Could you provide a commit message body to explain how merging the Zeroable and Subtractable types will eliminate Xcode 9 failures?

2017-10-31 15:52 UTC, romoore commented on src/protocols/ZeroableAndSubtractable.swift
> + Copyright 2016-present The Material Motion Authors. All Rights Reserved.
Please update the copyright to 2017.

2017-10-31 16:01 UTC, jverkoey commented
Done.

2017-10-31 16:02 UTC, jverkoey commented on src/protocols/ZeroableAndSubtractable.swift
> + Copyright 2016-present The Material Motion Authors. All Rights Reserved.
Done.

2017-10-31 17:51 UTC, romoore approved these changes
LGTM

2017-10-31 17:52 UTC, merged

2018-07-31 12:15 UTC, benSmith1981 commented
Is this updated in the pod file? I get these errors if I instlal with the pod still